-- 🚀 MIGRATION V5 : RÉPARATION DES PARAMÈTRES & BOUTONS
-- Exécutez ce script dans l'éditeur SQL de Supabase (SQL Editor)

ALTER TABLE bot_settings 
ADD COLUMN IF NOT EXISTS custom_links TEXT DEFAULT '[]',
ADD COLUMN IF NOT EXISTS label_profile TEXT DEFAULT 'Profil',
ADD COLUMN IF NOT EXISTS ui_icon_profile TEXT DEFAULT '👤',
ADD COLUMN IF NOT EXISTS label_livreur_space TEXT DEFAULT 'Espace Livreur',
ADD COLUMN IF NOT EXISTS ui_icon_livreur TEXT DEFAULT '🚴',
ADD COLUMN IF NOT EXISTS label_admin_bot TEXT DEFAULT 'Admin Bot',
ADD COLUMN IF NOT EXISTS ui_icon_admin TEXT DEFAULT '⚙️',
ADD COLUMN IF NOT EXISTS label_admin_web TEXT DEFAULT 'LE PLUG IDF',
ADD COLUMN IF NOT EXISTS ui_icon_web TEXT DEFAULT '🌐',
ADD COLUMN IF NOT EXISTS label_welcome TEXT DEFAULT 'Bienvenue',
ADD COLUMN IF NOT EXISTS ui_icon_welcome TEXT DEFAULT '👋',
ADD COLUMN IF NOT EXISTS label_reviews TEXT DEFAULT 'Avis',
ADD COLUMN IF NOT EXISTS ui_icon_leave_review TEXT DEFAULT '⭐️',
ADD COLUMN IF NOT EXISTS ui_icon_view_reviews TEXT DEFAULT '👥',
ADD COLUMN IF NOT EXISTS label_users TEXT DEFAULT 'Utilisateurs',
ADD COLUMN IF NOT EXISTS label_info TEXT DEFAULT 'Informations',
ADD COLUMN IF NOT EXISTS ui_icon_info TEXT DEFAULT 'ℹ️',
ADD COLUMN IF NOT EXISTS btn_back_generic TEXT DEFAULT '◀️ Retour',
ADD COLUMN IF NOT EXISTS btn_back_quick_menu TEXT DEFAULT '◀️ Menu',
ADD COLUMN IF NOT EXISTS btn_back_to_cart TEXT DEFAULT '◀️ Retour Panier',
ADD COLUMN IF NOT EXISTS btn_back_to_qty TEXT DEFAULT '◀️ Retour Quantité',
ADD COLUMN IF NOT EXISTS btn_back_to_address TEXT DEFAULT '◀️ Retour Adresse',
ADD COLUMN IF NOT EXISTS btn_back_to_options TEXT DEFAULT '◀️ Retour aux options',
ADD COLUMN IF NOT EXISTS btn_back_to_livreur_menu TEXT DEFAULT '◀️ Menu Livreur',
ADD COLUMN IF NOT EXISTS btn_next TEXT DEFAULT '➡️ Suivant',
ADD COLUMN IF NOT EXISTS btn_previous TEXT DEFAULT '◀️ Précédent',
ADD COLUMN IF NOT EXISTS btn_clear_cart TEXT DEFAULT '🗑 Vider le panier',
ADD COLUMN IF NOT EXISTS btn_cancel_order TEXT DEFAULT '❌ Annuler la commande',
ADD COLUMN IF NOT EXISTS btn_cancel_my_order TEXT DEFAULT '❌ Annuler ma commande',
ADD COLUMN IF NOT EXISTS btn_abandon_delivery TEXT DEFAULT '❌ Abandonner la livraison',
ADD COLUMN IF NOT EXISTS btn_send_now TEXT DEFAULT '✅ Envoyer maintenant',
ADD COLUMN IF NOT EXISTS btn_help_support TEXT DEFAULT '❓ Aide & Support',
ADD COLUMN IF NOT EXISTS btn_where_is_delivery TEXT DEFAULT '📍 Où est ma livraison ?',
ADD COLUMN IF NOT EXISTS btn_cancel TEXT DEFAULT '◀️ Annuler',
ADD COLUMN IF NOT EXISTS btn_cancel_alt TEXT DEFAULT '❌ Annuler',
ADD COLUMN IF NOT EXISTS btn_dont_use_credit TEXT DEFAULT '❌ Non, payer plein tarif',
ADD COLUMN IF NOT EXISTS btn_set_available TEXT DEFAULT '✅ Passer en Disponible',
ADD COLUMN IF NOT EXISTS btn_notify_30min TEXT DEFAULT '⏳ Arrivée dans 30 min',
ADD COLUMN IF NOT EXISTS btn_notify_10min TEXT DEFAULT '⏳ Arrivée dans 10 min',
ADD COLUMN IF NOT EXISTS btn_rate_5 TEXT DEFAULT '⭐️⭐️⭐️⭐️⭐️',
ADD COLUMN IF NOT EXISTS btn_rate_4 TEXT DEFAULT '⭐️⭐️⭐️⭐️',
ADD COLUMN IF NOT EXISTS btn_rate_3 TEXT DEFAULT '⭐️⭐️⭐️',
ADD COLUMN IF NOT EXISTS btn_rate_2 TEXT DEFAULT '⭐️⭐️',
ADD COLUMN IF NOT EXISTS btn_rate_1 TEXT DEFAULT '⭐️',
ADD COLUMN IF NOT EXISTS msg_session_expired TEXT DEFAULT '❌ Session expirée.',
ADD COLUMN IF NOT EXISTS msg_product_not_found TEXT DEFAULT '❌ Produit non trouvé.',
ADD COLUMN IF NOT EXISTS msg_order_not_available TEXT DEFAULT '❌ Commande non disponible.',
ADD COLUMN IF NOT EXISTS msg_order_not_found TEXT DEFAULT '❌ Commande non trouvée.',
ADD COLUMN IF NOT EXISTS msg_order_creation_error TEXT DEFAULT '❌ Erreur création commande.',
ADD COLUMN IF NOT EXISTS msg_not_livreur TEXT DEFAULT '❌ Vous n''êtes pas livreur.',
ADD COLUMN IF NOT EXISTS msg_access_denied TEXT DEFAULT '❌ Accès refusé.',
ADD COLUMN IF NOT EXISTS msg_catalog_empty TEXT DEFAULT '🛒 Le catalogue est vide.',
ADD COLUMN IF NOT EXISTS msg_cart_empty TEXT DEFAULT '🛒 Votre panier est vide.',
ADD COLUMN IF NOT EXISTS msg_no_reviews_yet TEXT DEFAULT '👥 Aucun avis pour le moment.',
ADD COLUMN IF NOT EXISTS msg_no_information TEXT DEFAULT 'ℹ️ Aucune information disponible.',
ADD COLUMN IF NOT EXISTS msg_no_active_deliveries TEXT DEFAULT '🛵 Aucune livraison active.',
ADD COLUMN IF NOT EXISTS msg_empty_delivery_history TEXT DEFAULT '🛵 Historique vide.',
ADD COLUMN IF NOT EXISTS msg_no_active_orders TEXT DEFAULT '📦 Aucune commande en cours.',
ADD COLUMN IF NOT EXISTS msg_cart_cleared TEXT DEFAULT '🛒 Panier vidé.',
ADD COLUMN IF NOT EXISTS msg_thanks_for_feedback TEXT DEFAULT '🙏 Merci pour votre retour !',
ADD COLUMN IF NOT EXISTS msg_location_updated TEXT DEFAULT '📍 Position mise à jour.',
ADD COLUMN IF NOT EXISTS msg_livreur_welcome TEXT DEFAULT '🛵 Bienvenue dans l''espace livreur !';

-- Recharger le cache du schéma PostgREST
NOTIFY pgrst, 'reload schema';
